services:
  - type: worker
    name: telegram-movie-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download ru_core_news_sm
    startCommand: python bot.py
